option(RATOS_BUILD_SHARED "Build the shared Ratatoskr library" ON)
option(RATOS_BUILD_STATIC "Build the static Ratatoskr library" ON)
option(RATOS_BUILD_CLI "Build the ratos CLI" ON)
option(RATOS_BUILD_TESTS "Build native tests" ${BUILD_TESTING})
option(RATOS_ENABLE_SANITIZERS "Enable AddressSanitizer and UndefinedBehaviorSanitizer" OFF)
option(RATOS_BUILD_FUZZERS "Build libFuzzer DNS targets (Clang only)" OFF)

if(NOT RATOS_BUILD_SHARED AND NOT RATOS_BUILD_STATIC)
    message(FATAL_ERROR "At least one of RATOS_BUILD_SHARED or RATOS_BUILD_STATIC must be enabled")
endif()
if(RATOS_BUILD_FUZZERS AND NOT RATOS_BUILD_STATIC)
    message(FATAL_ERROR "RATOS_BUILD_FUZZERS requires RATOS_BUILD_STATIC")
endif()
if(RATOS_BUILD_TESTS AND NOT RATOS_BUILD_STATIC)
    message(FATAL_ERROR "RATOS_BUILD_TESTS requires RATOS_BUILD_STATIC for private parser tests")
endif()
if(RATOS_BUILD_FUZZERS AND NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "RATOS_BUILD_FUZZERS requires Clang/libFuzzer")
endif()
